name: Build Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
    
env: 
  ACR: "acrgitops"
  infraRepo: "Rollson/nginx-k8s-manifest"

jobs:

  build-image:
    runs-on: ubuntu-latest
    outputs:
      commit_sha_short: ${{ steps.commit_sha.outputs.sha_short }}
    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: short commit sha
      id: commit_sha
      run: echo "sha_short=$(git log -1 --pretty=%h)" >> $GITHUB_OUTPUT

    - name: print commit sha
      run: echo ${{ steps.commit_sha.outputs.sha_short }}

    - name: Build the Docker image
      run: |
        docker build --build-arg COMMIT_SHORT_SHA=${{ steps.commit_sha.outputs.sha_short }} . --file ./app/Dockerfile --tag ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}/nginx:${{ steps.commit_sha.outputs.sha_short }}

    - name: push container image
      run: |
        docker push ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}/nginx:${{ steps.commit_sha.outputs.sha_short }}

  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Rollson/nginx-k8s-manifest
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: setup git config 
        run: |
          git config --global user.email "rollsonipo@gmail.com"
          git config --global user.name "Rollson"
          echo ${{ needs.build-image.outputs.commit_sha_short }}
          sed -i "s#${{ env.ACR }}.*#${{ env.ACR }}.azurecr.io/nginx:${{ needs.build-image.outputs.commit_sha_short }}#g" dev/deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ needs.build-image.outputs.commit_sha_short }}"
          git push origin main
      - run: echo ${{ github }}
      # - run: git push origin main
      # git remote add github ${{ env.infraRepo }}