name: Build Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: short commit sha
      id: commit_sha
      run: echo "sha_short=$(git log -1 --pretty=%h" >> $GITHUB_OUTPUT

    - name: print commit sha
      run: echo ${{ steps.commit_sha.outputs.sha_short }}

    # - name: Build the Docker image
    #   run: |
    #     # docker build . --file Dockerfile --tag nginx:$(date +%s)
    #     docker build --build-arg COMMIT_SHORT_SHA=${{ git log -1 --pretty=%h }} . --file Dockerfile --tag nginx:${{ git log -1 --pretty=%h }}

    # - name: push container image
    #   run: |
    #     docker push ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}/$nginx:${{ git log -1 --pretty=%h }}
