name: Build Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
    
jobs:

  build-image:
    runs-on: ubuntu-latest
    outputs:
      commit_sha_short: ${{ steps.commit_sha.outputs.sha_short }}
    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: short commit sha
      id: commit_sha
      run: echo "sha_short=$(git log -1 --pretty=%h)" >> $GITHUB_OUTPUT

    - name: print commit sha
      run: echo ${{ steps.commit_sha.outputs.sha_short }}

    - name: Build the Docker image
      run: |
        docker build --build-arg COMMIT_SHORT_SHA=${{ steps.commit_sha.outputs.sha_short }} . --file ./app/Dockerfile --tag ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}/nginx:${{ steps.commit_sha.outputs.sha_short }}

    - name: push container image
      run: |
        docker push ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}/nginx:${{ steps.commit_sha.outputs.sha_short }}

  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.MANIFEST_REPO }}
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: update maifest and push changes 
        run: |
          git config --global user.email ${{ secrets.MANIFEST_REPO }}
          git config --global user.name ${{ secrets.REPO_USERNAME }} 
          echo ${{ needs.build-image.outputs.commit_sha_short }}
          sed -i "s#${{ secrets.ACR_REPO_NAME }}.*#${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER  }}/nginx:${{ needs.build-image.outputs.commit_sha_short }}#g" dev/deployment.yaml
          git add -A
          git commit -am "Image Update for - ${{ needs.build-image.outputs.commit_sha_short }}"
          git push origin main